### ISSUE TITLE
Nothing found

### ISSUE THREAD

**Issue by shahid921** [jahirfiquitiva/Frames#108]
### Expected behavior

I uploaded the wallpapers and json file on github and set the json file raw uri in strings.xml but when the app runs it keeps showing loading content... and when i switch to another tab it shows nothing found, what to do? help plz

**Comment by shahid921** [comment]
https://github.com/shahid111111/wallpapers/blob/master/wallpapers.json

<blockquote><img src="https://avatars0.githubusercontent.com/u/35474252?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/shahid111111/wallpapers">shahid111111/wallpapers</a></strong></div><div>Contribute to shahid111111/wallpapers development by creating an account on GitHub.</div></blockquote>

**Comment by jahirfiquitiva** [comment]
Use [jsonlint.com](http://jsonlint.com) to verify the structure of the json.
