### ISSUE TITLE
Feature Request: Add Static image when loading wallpaper thumbnail

### ISSUE THREAD

**Issue by sarsamurmu** [jahirfiquitiva/Frames#109]
### Is your feature request related to a problem? Please describe.

No My Feature Request not Related to a Problem.

### Describe the solution you'd like

This would be good if we could show a static image when a wallpaper thumbnail loads. There will be two image. One for light theme and one for dark theme. The image's format will be .png not SVGs. So, we can color it as we want.

### Additional context

Like in Backdrops App it shows it's app logo when wallpaper thumbnails are still loading.

![Backdrops App](https://i.imgur.com/OPCoSYT.png)

**Comment by code-quant** [comment]
Yeah, It will be awesome.
