### ISSUE TITLE
Duplicate Category

### ISSUE THREAD

**Issue by code-quant** [jahirfiquitiva/Frames#111]
I am using the latest version of frames. I am facing some issues with category tabs.
I am having duplicate categories.
Here is screenshot for reference: 
![photo6287330383720720538](https://user-images.githubusercontent.com/12227706/52906856-6649f580-327b-11e9-8863-5734a3227351.jpg)
My JSON: 

> {
"Categories": 
[
{"name": "4k"},
{"name": "Abstract"},
{"name": "Alphabets"},
{"name": "Amoled Flowers"},
{"name": "Amoled Nexus"},
{"name": "Animals and Birds"},
{"name": "Anime and Cartoon"},
{"name": "Architecture and Cityscape"},
{"name": "Artistic"},
{"name": "Bike and Cars"},
{"name": "Fire"},
{"name": "Fishes"},
{"name": "Logos"},
{"name": "Minimal"},
{"name": "Movies"},
{"name": "Nature"},
{"name": "Other"},
{"name": "Patterns"},
{"name": "People"},
{"name": "Silhouette"},
{"name": "Smoke"},
{"name": "Space"},
{"name": "Sports"},
{"name": "Stock Rom"},
{"name": "Typography"}   
],

**Comment by jahirfiquitiva** [comment]
Categories aren't taken from that array in the json file, but what you set in the wallpapers. Also, they are case sensitive.
