### ISSUE TITLE
Muzei Issue

### ISSUE THREAD

**Issue by code-quant** [jahirfiquitiva/Frames#112]
Wiki Says:
![screenshot_3](https://user-images.githubusercontent.com/12227706/52908089-55f24480-3294-11e9-8e40-a27bafa09033.png)

But there is nothing like `class MuzeiService:FramesArtSource("MyMuzeiService")` In project
![screenshot_2](https://user-images.githubusercontent.com/12227706/52908097-699dab00-3294-11e9-8d3d-014e66ab0d58.png)

**Comment by jahirfiquitiva** [comment]
The wiki is out of date. You don't need to do anything with the latest releases.

Next time use the proper issue template or your issues will be ignored.
