### ISSUE TITLE
Wall of the day support

### ISSUE THREAD

**Issue by ashvinstech** [jahirfiquitiva/Frames#114]
### Is your feature request related to a problem? Please describe.

No my feature request is not related to any problem.
### Describe the solution you'd like

Please add a wall of the day section in the all tab and the code in the json file so that we can add new walls everyday to that section
### Additional context

This is the reference like in backdrops app
![backdrops-wallpaper-2-980x653](https://user-images.githubusercontent.com/28800519/53281972-41f88800-3757-11e9-8dfb-31c06d60a244.jpg)

**Comment by usakha123** [comment]
This would be awesome
