### ISSUE TITLE
Automatic wallpaper changing function

### ISSUE THREAD

**Issue by ashvinstech** [jahirfiquitiva/Frames#116]
### Is your feature request related to a problem? Please describe.

No my feature request is not related to any problem.
### Describe the solution you'd like

Please add a feature of automatic wallpaper changing in the favourite section of the app itself without using "Muzei" so the app can auto change between all the favourite wallpapers like many other wallpaper  app do these days.

**Comment by jahirfiquitiva** [comment]
There's no need for this
