### ISSUE TITLE
Not all categories are shown

### ISSUE THREAD

**Issue by usakha123** [jahirfiquitiva/Frames#118]
- [x] I have verified that I am using the latest version.
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

### Device/App info:
 - Frames Version: `2.6.1`
 - Android version: `8.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi note 5 AI`

### Describe the bug
When the category page is reloaded not all the categories are shown

### Reproduction Steps
1.Open Frame app with a lot of categories
2.Reload the category section
3.Not all categories are shown

### Screenshots

[Video](https://drive.google.com/open?id=1f7MzlVK4Zm0zzEVJfvY0lGNPeUAd61vD)

**Comment by jahirfiquitiva** [comment]
The video doesn't help. Can you share the link to the json file?

**Comment by usakha123** [comment]
It's a bit long. [Here it is](https://raw.githubusercontent.com/IKAR0S/AnimPapers/master/Json/wallpaper.json)

**Comment by jahirfiquitiva** [comment]
@IKAR0S  The issue only happens after refresh, right?

**Comment by usakha123** [comment]
Yep

**Comment by ashvinstech** [comment]
It is also happening with me. It happens after you add about 10 categories.
