### ISSUE TITLE
"preview_url" Doesn't work in collections. 

### ISSUE THREAD

**Issue by ashvinstech** [jahirfiquitiva/Frames#129]
- [ yes] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ yes] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `2.6.5`
 - Android version: `9.0`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 6`

### Describe the bug

The "preview_url" doesn't work at all in the collections tab, if we put a preview image link in "preview_url" then also it loads an random preview image

### Reproduction Steps
1. Modify the app to load the "preview_url" if available

### Expected behavior

I except to load a preview image which is specified by me.

**Comment by jahirfiquitiva** [comment]
this is not a bug. simply check the [correct json format here](https://github.com/jahirfiquitiva/Frames/wiki/Setting-up-your-json-file)
