### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by SriRamTejaTelukuntla** [jahirfiquitiva/Frames#131]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `Latest`
 - Android version: `9, 8.1, 5.1`
 - Device Manufacturer: `Xiaomi, samsung, infinix`
 - Device Name: `MiA1, galaxy j2, infinix note 5`

### Describe the bug
App is crashing.

**Comment by jahirfiquitiva** [comment]
Don't paste stack traces here. Use pastebin.com

**Comment by jahirfiquitiva** [comment]
Also, provide more details: when is the crash happening? How can one replicate the issue?

**Comment by SriRamTejaTelukuntla** [comment]
https://pastebin.com/raw/SmkRzHSW

the app is crashing when we open 

<blockquote></blockquote>

**Comment by jahirfiquitiva** [comment]
please record a video of the issue. and are you using the master branch?

**Comment by SriRamTejaTelukuntla** [comment]
yes i'm using master branch and i got those crashes from playstore

**Comment by jahirfiquitiva** [comment]
Read the readme. I won't provide any kind of help when using the master branch. Stop it
