### ISSUE TITLE
The app crashing after clicking on "⬅"

### ISSUE THREAD

**Issue by masudr4n4** [jahirfiquitiva/Frames#133]
<h4>Actual behavior</h4>
The app crashes when i click the back sign in the top of screen.
<h4>Expected behavior</h4>
I expected that i can go back successfully after clicking the back sign without crashing the app.
<h4>How to reproduce</h4>
<ol>
<li>Open the app</li>
<li>wait for loading some content(make sure you have date connection).</li>
<li>click on a content to view</ki>
<li>Then click the "⬅" sign in the top of screen.</li>
<li>See the error.</li>
</ol>
<h4>Information</h4>
<ul>
    <li>App version: 2.6.8</li>
   <li> OS: Android 6.0.1</li>
   <li>Device: Samsung J5</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/512mrsqUSiI">https://youtu.be/512mrsqUSiI</a>
<h4>Logcat</h4>
<pre>
<code>04-14 10:43:29.980  9301  9301 E AndroidRuntime: FATAL EXCEPTION: main

04-14 10:43:29.980  9301  9301 E AndroidRuntime: Process: jahirfiquitiva.apps.frames.sample, PID: 9301

04-14 10:43:29.980  9301  9301 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.ActivityOptions.isReturning()' on a null object reference

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.app.ActivityTransitionState.startEnter(ActivityTransitionState.java:203)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.app.ActivityTransitionState.startPostponedEnterTransition(ActivityTransitionState.java:197)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.app.Activity.startPostponedEnterTransition(Activity.java:6788)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at androidx.core.app.a.d(Unknown Source)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at androidx.e.a.o.supportStartPostponedEnterTransition(Unknown Source)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at jahirfiquitiva.libs.frames.helpers.extensions.ActivityKt.safeStartPostponedEnterTransition(Unknown Source)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at jahirfiquitiva.libs.frames.ui.fragments.base.BaseWallpapersFragment$onActivityReenter$2.onPreDraw(Unknown Source)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2603)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7530)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:622)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-14 10:43:29.980  9301  9301 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</code>
</pr>

**Comment by aryansoni1108** [comment]
Please solve this bug as soon as possible.
