### ISSUE TITLE
JSON not updating 

### ISSUE THREAD

**Issue by akinhd** [jahirfiquitiva/Frames#147]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.0.0`
 - Android version: `10.0`
 - Device Manufacturer: `Onplus`
 - Device Name: `Oneplus 6`

### Describe the bug
When new wallpapers are added to Json, same is not appearing in the app. 

### Reproduction Steps
1.build a app with default walls. 
2. Add few new wallpapers, now open the to app to check them. 
3. New walls won't be seen until you clear the app data and reload it 

### Expected behavior
Every time the app is opened the Json has to be refreshed.

**Comment by jahirfiquitiva** [comment]
Should be fixed in v `3.0.1`
