### ISSUE TITLE
Thumbnail not loading images

### ISSUE THREAD

**Issue by DaFray31** [jahirfiquitiva/Frames#148]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.0.3`
 - Android version: `10`
 - Device Manufacturer: `Realme`
 - Device Name: `Realme 3 pro`

### Describe the bug
Thumbnail is not loading , also tiles are empty, Tiles are just colored to the primary color

### Reproduction Steps
1. When i open the app, and Thumbnail  are not loading also same for collections

**Comment by jahirfiquitiva** [comment]
I'm unable to reproduce the issue so maybe check your json file and internet connection
