### ISSUE TITLE
Downloaded wallpapers don't appear in gallery apps

### ISSUE THREAD

**Issue by MHcharLEE** [jahirfiquitiva/Frames#157]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.1.9`
 - Android version: `10`
 - Device Manufacturer: `OnePlus`
 - Device Name: `6T A6013`

### Describe the bug
Using Frames 3.1.9, sample, unmodified in any way. I push the app to my phone with Android Studio (up to date), proceed to download any wallpaper provided by Jahir with the default JSON. The download is successful, the file is in proper storage/pictures/frames folder. The file does NOT appear in OEM Gallery app, recent files, or in media selector (i.e. uploading a photo in an FB messenger conversation/discord).

Changing the file name works in making the image be "visible" sometimes, but not always, unsure if there's a pattern to this.

### Reproduction Steps
1. Open sample frames 3.1.9 in Android Studio
2. Push the app to phone
3. Download any wallpaper provided with the default JSON
4. Wallpaper not visible in OEM gallery app or media selector/wallpaper selector

### Expected behavior
Wallpaper visible everywhere in the system just like a regular photo would be.

**Comment by jahirfiquitiva** [comment]
Fixed. Will be available in next update
