### ISSUE TITLE
Wallpapers zoomed when selected

### ISSUE THREAD

**Issue by DanyGee** [jahirfiquitiva/Frames#158]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.2.0 (Blueprint 2.0.0)`
 - Android version: `9`
 - Device Manufacturer: `LG`
 - Device Name: `LGv30`

### Describe the bug
Wallpapers not scale properly when chosen.
User needs to move the wallpaper and then it scales properly.

### Reproduction Steps
1. Enter wallpapers section
2. Choose a wallpaper
3. Now u can see its zoomed too much
4. Move the wallpaper left or right and notice it scales to screen

### Expected behavior

Wallpaper should be properly scaled once chosen. Not zoomed.

### Screenshots

Selection
![Screenshot_20200418-110412](https://user-images.githubusercontent.com/26818551/79633248-91bcbe80-8164-11ea-8175-05a222cbd25a.png)

Initial zoom
![Screenshot_20200418-110420](https://user-images.githubusercontent.com/26818551/79633266-aa2cd900-8164-11ea-944a-aff1595aaa79.png)

After moving the wallpaper
![Screenshot_20200418-110425](https://user-images.githubusercontent.com/26818551/79633301-d6485a00-8164-11ea-89cb-778b88759831.png)

### Additional context

Using Blueprint 2.0.0

**Comment by jahirfiquitiva** [comment]
This gets "fixed" by disabling animations or removing the `ImageView` from shared elements

**Comment by DanyGee** [comment]
Well, it works, but I think it should be considered as a workaround rather than a "fix".
Do you plan to really fix it?

**Comment by jahirfiquitiva** [comment]
I've made a "fix"... This is all I will do for now, but will keep it in mind for the future

**Comment by jahirfiquitiva** [comment]
Check progress and updates on #165
