### ISSUE TITLE
Change wallpapers based on system theme

### ISSUE THREAD

**Issue by Martin5001** [jahirfiquitiva/Frames#168]
Would it be possible to add an option to create a set of two wallpapers which would automatically change depending on the system light/dark theme on Android 9 and higher?
There could be a simple icon in the corner of the thumbnail and if the user chose this dynamic wallpaper, he would be asked whether or not he wants to change the wallpaper dynamically or use just the one of the images (light/dark).

**Comment by jahirfiquitiva** [comment]
Unfortunately, I'm not going to do that
