### ISSUE TITLE
The first time you run the app after installation, there will be such a bug.

### ISSUE THREAD

**Issue by AmazingMachine** [jahirfiquitiva/Frames#176]
The first time you run the app after installation, there will be such a bug.
The second run will not appear.

Test device pixel xl android 10
The test has been repeated many times

bug description: When the app is opened for the first time, after the splashscreen appears, a strange prompt of ‘no wallpaper’ will appear, and then the loading wallpaper will be displayed. This phenomenon will not appear in the second run of the app.

![device-2020-05-27-145339_gif_001](https://user-images.githubusercontent.com/28883779/82988172-56e35b80-a02b-11ea-85c9-d774598e8091.gif)

**Comment by Martin5001** [comment]
For me this issue occurs everytime on opening, not just after installation. Pulling down to refresh fixes it. This is, however, in the integrated wallpaper frames section used in Blueprint-based icon pack (Blueprint 2.1.2), not the Frames-based wallpaper app itself. I believe it's related though so adding here.

**Comment by jahirfiquitiva** [comment]
Will be improved in next update
