### ISSUE TITLE
Firebase Issue

### ISSUE THREAD

**Issue by L0nelyW0lf** [jahirfiquitiva/Frames#19]
Iam getting this issue after following wiki in firebase 

Error:Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by jahirfiquitiva** [comment]
The issue is not related with Frames, but Android Studio.

Be sure to have the Kotlin plugin installed

**Comment by L0nelyW0lf** [comment]
ooh but i have installed Kotlin

**Comment by jahirfiquitiva** [comment]
Then post the whole logs because what you posted does not provide any real info

**Comment by jahirfiquitiva** [comment]
Please post the whole logs because what you posted does not provide enough info

**Comment by L0nelyW0lf** [comment]
Am trying to post it i dont know where to take thats what am googling it

**Comment by jahirfiquitiva** [comment]
Closing this as not enough info was provided

**Comment by jahirfiquitiva** [comment]
Please make sure you follow the steps in [the wiki](https://github.com/jahirfiquitiva/Frames/wiki/Adding-Firebase-support) exactly as they are listed.

**Comment by L0nelyW0lf** [comment]
its working the issue is kotlin version
