### ISSUE TITLE
Changing "Show Wallpapers From" setting in Muzei Integration can't remove collections, only add.

### ISSUE THREAD

**Issue by ctlyst** [jahirfiquitiva/Frames#192]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.3.3`
 - Android version: `10`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 3a`

### Describe the bug
Ticking a collection in the `Show Wallpapers From` settings in the Muzei Integration menu will add those wallpapers when you go to the `Browse` tab on Muzei which is a good thing.

The collection `food` has 3 images in it, and Muzei shows it correctly, which is a good thing.
![image](https://user-images.githubusercontent.com/46639525/90762611-e5f4cc80-e317-11ea-9162-0ee04a2e0193.png)

But when you remove the `food` collection and add the `city` collection, Muzei should just show 4 images but this is not the case. It seems that the last collection which is `food` is still there even though it should be removed. 
![image](https://user-images.githubusercontent.com/46639525/90762892-5d2a6080-e318-11ea-9bd2-2a397c6b1016.png)

Adding a different collection does the same thing, but now it's just that collection and every collection before it, even if those collections was removed in the settings.

### Reproduction Steps (Uses Frames app on releases)
1. Open `Muzei`
2. Set `Frames` as wallpaper provider
3. Click `Settings`
4. Click `Show Wallpapers From`
5. Tick `food` then click `OK`
6. Press back
7. Click `Browse`
8. Refresh by swiping down or using the overflow menu. It should now have 3 images.
9. Press back
10. Repeat steps 3 to 8 but untick `food` and tick `city` on the `Show Wallpapers From` dialog
11. Now there should be 7 images (4 from `city` + 3 from `food`) instead of 4

### Expected behavior
There should have been only 4 images on `Browse` because it should've removed the images from the `food` collection. Instead it just appends the 4 images from the `city` collection.

### Screenshots
![image](https://user-images.githubusercontent.com/46639525/90764027-46850900-e31a-11ea-842b-fb2fac99a938.png)

**Comment by jahirfiquitiva** [comment]
Fixed in next version
