### ISSUE TITLE
"cannot find browser" for TOS and privacy links / dashboard_setup.xml

### ISSUE THREAD

**Issue by ghost** [jahirfiquitiva/Frames#198]
` 
    <string name="terms_conditions_link">"https://www.t-ryder.de/imprint/"</string>`

Gives me a toast message saying "cannot find a browser" - latest Android 11 on Pixel 2 XL and on Android 10 virtual device.

Frames v3.3.3

**Comment by ghost** [comment]
Same goes for the about section of the app. Website links give "cannot find a browser"

**Comment by jahirfiquitiva** [comment]
Please use one of the issue templates
