### ISSUE TITLE
Remove the Collection Tab and Just have ALL and Favorites ?

### ISSUE THREAD

**Issue by motionwallpapers** [jahirfiquitiva/Frames#20]
Is it possible in my code to remove the Collection Tab and Just have ALL and Favorites ?
Most of the wallpapers are vertical so that the images show in the collection thumbnail is a bit off 

Or is it possible to put a particular thumbnail for the the collection page tabs ?

**Comment by jahirfiquitiva** [comment]
It will be possible to remove the collection tab in next update.
