### ISSUE TITLE
Strange behaviour when applying wallpaper

### ISSUE THREAD

**Issue by hynra** [jahirfiquitiva/Frames#203]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `v 3.3.5`
 - Android version: `10`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy A50`

### Describe the bug
I don't know exactly what the problem is, but some of the wallpapers I have set can be partially applied, but some can't. See the example below, this wallpaper cannot be applied

```
https://i.imgur.com/DsTXC9b.jpg
```

But this one can be applied, even though on the same host.

```
https://i.imgur.com/OmEEchX.jpg
```

I have done some tracing, for wallpaper that can't be applied this is because the buffer `len` read zero

https://github.com/jahirfiquitiva/Frames/blob/03b92e115ccf2914b3fafe19e1ff136af32947a4/library/src/main/kotlin/dev/jahir/frames/data/workers/WallpaperApplier.kt#L107

### Reproduction Steps
1. Load wallpaper that can't be applied. For example https://i.imgur.com/DsTXC9b.jpg
2. Apply Wallpaper
3. Something went wrong's toast appeared

### Expected behavior
Wallpaper applied

### Code and/or Logs
I cannot provide logs because there is no suspicious log appeared

**Comment by hynra** [comment]
I submitted PR to fix this issue, change from `URLConnection` to `OkHttpClient` solved this problem.

**Comment by jahirfiquitiva** [comment]
Thanks for your contribution, will test it this weekend and merge it if everything goes well.
