### ISSUE TITLE
[Feature Request] Automatic Wallpaper Changer 

### ISSUE THREAD

**Issue by UnFunnyGuy** [jahirfiquitiva/Frames#209]

**Comment by UnFunnyGuy** [comment]
Automatic Wallpaper Changer from favourites on a hourly and daily intervals.

Just A request 🥺👉👈

**Comment by jahirfiquitiva** [comment]
1. The issue does not have the right issue template.
2. This is already doable via Muzei, so I won't add such feature, sorry.
