### ISSUE TITLE
App Crashes after saving 2-5 wallpapers in Android 11

### ISSUE THREAD

**Issue by panchammsinghh** [jahirfiquitiva/Frames#215]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.3.7`
 - Android version: `Android 11`
 - Device Manufacturer: `Samsung and Google`
 - Device Name: `Note 20 Ultra and Pixel 4`

### Describe the bug
After setting up things on Android Studio, I found the app is working fine on the Android 10 and Android Pie, but in Android 11 it is crashing, after saving (downloading) a few images, sometimes it crashes after saving 3-4 images and sometime after 1-2 images.

The logs showing these during crash - 

dev.jahir.frames.ui.activities.base.BaseThemedActivity.onCreate (BaseThemedActivity.java:3)
dev.jahir.frames.ui.activities.base.BaseFavoritesConnectedActivity.onCreate (BaseFavoritesConnectedActivity.java)
dev.jahir.frames.ui.activities.base.BaseBillingActivity.onCreate (BaseBillingActivity.java)
dev.jahir.frames.ui.activities.FramesActivity.onCreate (FramesActivity.java)

**Comment by jahirfiquitiva** [comment]
@panchammsinghh is this still happening with v 3.4.2 ?

**Comment by panchammsinghh** [comment]
Yes :-( Same problem when click on Save (Download button) application will automatically crashes and go back to smartphone app drawer.  Sometime it crashes on first download, while some time, after downloading two-three images.

Tested on Android Emulator (Android 11), OnePlus 8 Pro, Samsung Galaxy A51, S21, M51.

![image](https://user-images.githubusercontent.com/61957280/118144998-b6986980-b42a-11eb-861b-693ad9072ebc.png)

Screenshot taken after crashing.
