### ISSUE TITLE
Black bars on wallpaper viewer on phones with notches

### ISSUE THREAD

**Issue by lorandcompany** [jahirfiquitiva/Frames#217]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.3.7`
 - Android version: `11`
 - Device Manufacturer: `POCO`
 - Device Name: `POCO X3 NFC`

### Describe the bug
A black bar shows when you go fullscreen on the wallpaper viewer.

### Reproduction Steps
1. Have a phone with a notch
2. Go fullscreen on wallpaper viewer

### Expected behavior

Theres a black bar above.

### Screenshots

https://streamable.com/750bvj

**Comment by codenameakshay** [comment]
This issue can be fixed by adding this line `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` in `app/src/main/res/values/styles.xml`, in each `<style>` tag.

Example - 
```
    <style name="MyApp.SplashScreen" parent="Frames.SplashScreen.Amoled">
        <item name="customFontBold">@font/epilogue_semibold_fam</item>
        <item name="customFontNormal">@font/epilogue_regular_fam</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item> // Add this line
    </style>

    <!-- Don't change the parent style -->
    <style name="MyApp.Default" parent="Frames.Default">
        <item name="bottomNavigationStyle">@style/MyApp.BottomNavigationView</item>
        <item name="customFontBold">@font/epilogue_semibold_fam</item>
        <item name="customFontNormal">@font/epilogue_regular_fam</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item> // Add this line
    </style>

    <!-- Don't change the parent style -->
    <style name="MyApp.Default.Amoled" parent="Frames.Default.Amoled">
        <item name="bottomNavigationStyle">@style/MyApp.BottomNavigationView</item>
        <item name="customFontBold">@font/epilogue_semibold_fam</item>
        <item name="customFontNormal">@font/epilogue_regular_fam</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item> // Add this line
    </style>
```

**Comment by jahirfiquitiva** [comment]
thanks for sharing @codenameakshay
