### ISSUE TITLE
Download wallpaper on WiFi only option not working

### ISSUE THREAD

**Issue by SUSANTA151** [jahirfiquitiva/Frames#222]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.4.3`
 - Android version: `8.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto Z Play`

### Describe the bug
If this option in settings (_**Download wallpapers on WiFi only**_) is only available to download wallpaper on WiFi, it does not work. "**Download wallpapers on WiFi only**" is turned on but still, the Wallpapers are downloaded on the mobile network. 

### Expected behavior
If the option is turn on and the user trying to download a wallpaper, a notification should appear and says that "**Waiting for WiFi**" and an option "**Download now**".

**Comment by jahirfiquitiva** [comment]
Should be fixed with v 3.4.4
