### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [jahirfiquitiva/Frames#231]
### Frames Version

3.4.6

### Describe the feature

There are only 4 translations with coverage in as many years.
The maker of one of those is already moving his projects.
I see every reason to move. The better tool has the better license, and is available on better terms
as a hosted service.

### Describe alternatives you have considered

https://weblate.bubu1.eu/ , https://hosted.weblate.org/ or self-hosted.

Translatewiki, Zanata, Pontoon, etc.

### Additional context or info

https://hosted.weblate.org/hosting/ applies

**Comment by jahirfiquitiva** [comment]
Can you elaborate on your request? I didn't understand a thing

**Comment by comradekingu** [comment]
@jahirfiquitiva 
I was thinking that for the translation platform, Weblate could be used.
Then more languages could be available, with better quality :)

**Comment by jahirfiquitiva** [comment]
I don't think changing the translations platform is needed or worth the effort, sorry
