### ISSUE TITLE
Non-free license on the wiki

### ISSUE THREAD

**Issue by comradekingu** [jahirfiquitiva/Frames#232]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

3.6.4

### Android Version

11

### Device Manufacturer

Motorola

### Device Name

g6

### What happened?

https://github.com/jahirfiquitiva/Frames/wiki

### Reproduction Steps

Says CC BY-_NC_-SA 4.0 at the bottom

### Expected behavior

Was thinking it would be the same as https://github.com/jahirfiquitiva/Frames/blob/sample/LICENSE.md
and a software license would probably be better.

**Comment by jahirfiquitiva** [comment]
That's the wiki content license, not the dashboard. Don't worry
