### ISSUE TITLE
Download Wallpapers

### ISSUE THREAD

**Issue by SamNeill** [jahirfiquitiva/Frames#234]
### Frames Version

3.4.6

### Describe the feature

* Please add an option to set a default behavior for download wallpapers on any connection Data or WiFi without turning on switch

### Describe alternatives you have considered

*Mostly people don't use that switch and start complaining or don't wanna go there or maybe don't know that thing is there...I

**Comment by jahirfiquitiva** [comment]
This can be done using option `downloads_on_wifi_only_enabled_by_default`
