### ISSUE TITLE
How to change notification icon?

### ISSUE THREAD

**Issue by L0nelyW0lf** [jahirfiquitiva/Frames#24]
###### Device/dashboard info:
 - Frames version: `2.0.9`
 - Device OS version: `7.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `S7 Edge`

May i know how to change Notification icon?

**Comment by jahirfiquitiva** [comment]
Hi

Sorry, it seems I forgot to mention it in the wiki. You can already check it following [this link](https://github.com/jahirfiquitiva/Frames/wiki/Adding-Firebase-support#change-notifications-icon)

**Comment by L0nelyW0lf** [comment]
you didnt say where to put this ic_notifications.xml file. I meant the path.
thank u

**Comment by jahirfiquitiva** [comment]
@kingofwap  Just added that info... You can access it with the same link ... Sorry about it :/

**Comment by L0nelyW0lf** [comment]
its ok. thanks bro.
