### ISSUE TITLE
Add support for embedded Wallpapers

### ISSUE THREAD

**Issue by johnuopini** [jahirfiquitiva/Frames#253]
### Kuper Version

2.4.4

### Describe the feature

I understand having a JSON makes sense in most use cases but it would be very useful to have an option to embed the wallpapers in the APK itself just like we do with Kustom files, then the json could be the very same but the resources URL would be something like "asset://wallpapers/filename.png" rathen then an HTTP uri.

### Additional context or info

Not always user is connected and might want to switch wallpaper quickly

**Comment by jahirfiquitiva** [comment]
@johnuopini I can confirm this is already working. Check the [sample json file](https://jahir.dev/frames/frames.json) for an example:

**Comment by jahirfiquitiva** [comment]
@johnuopini Added some docs here: https://github.com/jahirfiquitiva/Kuper/wiki/Setting-up-your-wallpapers-json-file/#wallpapers-images-from-assets

<blockquote><img src="https://opengraph.githubassets.com/2494720720e17f8523d03cce29c35f263f09f3dd65f7866fe9b0636ea959f6c3/jahirfiquitiva/Kuper" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jahirfiquitiva/Kuper/wiki/Setting-up-your-wallpapers-json-file">Setting up your wallpapers json file</a></strong></div><div>Free, feature-rich, easily customizable Android dashboard for widgets apps with Zooper widgets and/or Kustom assets (Widgets, Wallpapers and Komponents) - jahirfiquitiva/Kuper</div></blockquote>

**Comment by johnuopini** [comment]
> @johnuopini Added some docs here: https://github.com/jahirfiquitiva/Kuper/wiki/Setting-up-your-wallpapers-json-file/#wallpapers-images-from-assets

Great stuff!! Will test asap, thanks!!


<blockquote><img src="https://opengraph.githubassets.com/7b5d480e87f5be4c85c546b97b86f606cde8630886c31a4d194e4b2ded9fcb4a/jahirfiquitiva/Kuper" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jahirfiquitiva/Kuper/wiki/Setting-up-your-wallpapers-json-file">Setting up your wallpapers json file</a></strong></div><div>Free, feature-rich, easily customizable Android dashboard for widgets apps with Zooper widgets and/or Kustom assets (Widgets, Wallpapers and Komponents) - jahirfiquitiva/Kuper</div></blockquote>
