### ISSUE TITLE
Predictive back gesture not working on Android 14

### ISSUE THREAD

**Issue by pashapuma** [jahirfiquitiva/Frames#256]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

3.5.5

### Android Version

14

### Device Manufacturer

Google

### Device Name

Pixel 7

### What happened?

android:enableOnBackInvokedCallback="true" no work! It used to work before you added it to the manifest... I added it to the Manifest with the release of this feature and it worked, but after you added it to the project it stopped!

### Reproduction Steps

android:enableOnBackInvokedCallback="true"

**Comment by jahirfiquitiva** [comment]
@pashapuma 

> android:enableOnBackInvokedCallback="true" no work!

What exactly does not work?

> It used to work before you added it to the manifest

What used to work before? What Frames version is "before"?

-----

The reproduction steps are not clear and not complete, so please elaborate on that.

Also, if you can add screenshots or logs about the error, please do.

**Comment by pashapuma** [comment]
No work - predictive back gesture. Does not work after Update to Frames v 3.5.1.
There was a change +android:enableOnBackInvokedCallback="true" in the AndroidManifest.
after that it doesn't work. Before this version, I added Gesture back itself - and it worked perfectly.

**Comment by pashapuma** [comment]
https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture

<blockquote><img src="https://developer.android.com/static/images/social/android-developers.png" width="48" align="right"><div>Android Developers</div><div><strong><a href="https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture">Add support for the predictive back gesture  |  Android Developers</a></strong></div></blockquote>

**Comment by jahirfiquitiva** [comment]
@pashapuma

> I added Gesture back itself

How did you do this?

**Comment by pashapuma** [comment]
I just had to add the line
<application
     ...
     android:enableOnBackInvokedCallback="true"
     ... >
...
</application>

no more changes. and it worked on version below v 3.5.1

**Comment by jahirfiquitiva** [comment]
@pashapuma got it, will investigate what could have changed since that version that broke it.

**Comment by jahirfiquitiva** [comment]
Will be fixed in the next update
