### ISSUE TITLE
Slow UI with a large amount of (~15k) wallpapers

### ISSUE THREAD

**Issue by Yureien** [jahirfiquitiva/Frames#26]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Frames.

###### Device/dashboard info:
 - Frames version: `2.1.1`
 - Device OS version: `API 27 (8.1.0)`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps

1. The usual app-building steps with [this JSON file](http://sohamsen.me/uploads/out.json).
2. Open and use the app.

###### Expected Result

Fast UI.

###### Actual Result

Very slow UI. Search works slowly, and hangs often. It takes ~30 seconds for the app to load each time.

**Comment by Yureien** [comment]
I have pinpointed it to this line - `parseListFromJson(param, response)`. This takes ~30 seconds.

**Comment by jahirfiquitiva** [comment]
Hi @FadedCoder 

I have spent a few hours trying to address this issue and improve it, but unfortunately can't provide any better solution for now, especially given that this is a very specific use case of the app and you must be aware that 15K wallpapers is a really huge and considerable amount of wallpapers.

My suggestions:
1. Be sure to use a fast server.
2. Think about all users. Not everyone will have a super fast connection to load such a big amount of data. (JSON file is almost 10Mb)
3. Reduce the amount of wallpapers. I'm sure nobody will check 15K wallpapers. Even 5K is a fairly good amount.
4. Optimize the wallpapers so they load faster.

If you don't want to apply any of these, or you do but no significant improvements are visible, then I kindly encourage you to fork the project and contribute to it by doing the required improvements. I will be sure to check and accept your changes if I consider they improve the dashboard. And I'm sure you will help a lot of people out there too.

Thanks for using Frames.
![bitmoji](https://render.bitstrips.com/v2/cpanel/c10864c1-2acd-4397-89d0-3a5667aab6d2-f1a30f5f-4907-483f-874a-54b05c8475ab-v1.png?transparent=1&palette=1&width=246)

**Comment by Yureien** [comment]
I've partly solved this issue. In addition to the above, I've also used
done this -

I modified the code a bit so that it checks for the hash first from the
net, and if the hash is changed, it'll fetch the whole json.

**Comment by jahirfiquitiva** [comment]
@FadedCoder 
Would you mind if I implement your code in the original dashboard?

**Comment by Yureien** [comment]
Yeah sure, I have forked the repository.
