### ISSUE TITLE
Unresolved reference: app

### ISSUE THREAD

**Issue by pexeixv** [jahirfiquitiva/Frames#260]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

3.5.6

### Android Version

13

### Device Manufacturer

Nothing

### Device Name

Phone (1)

### What happened?

Getting this error
```bash
e: file:///D:/Android/Madridista%20Wallpapers/app/src/main/kotlin/in/gavinpereira/madridista/MainActivity.kt:3:25 Unresolved reference: app
```

My `MainActivity.kt` looks like this
```kt
package `in`.gavinpereira.madridista
import com.github.javiersantos.piracychecker.PiracyChecker
import dev.jahir.frames.app.R
import dev.jahir.frames.ui.activities.FramesActivity

class MainActivity : FramesActivity() {

    /**
     * These things here have the default values. You can delete the ones you don't want to change
     * and/or modify the ones you want to.
     */
    override val billingEnabled = true

    override fun amazonInstallsEnabled(): Boolean = false
    override fun checkLPF(): Boolean = true
    override fun checkStores(): Boolean = true

    /**
     * This is your app's license key. Get yours on Google Play Dev Console.
     * Default one isn't valid and could cause issues in your app.
     */
    override fun getLicKey(): String? = "MIIBIjANBgkqhkiGgKglYGYGihLuihUuhhuBlouBkuiu"

    /**
     * This is the license checker code. Feel free to create your own implementation or
     * leave it as it is.
     * Anyways, keep the 'destroyChecker()' as the very first line of this code block
     * Return null to disable license check
     */
    override fun getLicenseChecker(): PiracyChecker? {
        destroyChecker() // Important
        return if (BuildConfig.DEBUG) null else super.getLicenseChecker()
    }

    override fun defaultTheme(): Int = R.style.MyApp_Default
    override fun amoledTheme(): Int = R.style.MyApp_Default_Amoled

    override fun defaultMaterialYouTheme(): Int = R.style.MyApp_Default_MaterialYou
    override fun amoledMaterialYouTheme(): Int = R.style.MyApp_Default_Amoled_MaterialYou
}

```

### Reproduction Steps

I just followed the steps in the Wiki

### Expected behavior

Build success

**Comment by pexeixv** [comment]
Only had to change LOC 3 to : `import dev.jahir.frames.R`

**Comment by jahirfiquitiva** [comment]
@pexeixv 

as mentioned in the wiki, you must change the package name everywhere to be your app package.

therefore, you must change

`import dev.jahir.frames.app.R`

to

```kotlin
import `in`.gavinpereira.madridista.R
```


this isn't an issue with the dashboard, so please use Discord next time for support
https://discordapp.com/invite/78h7xgj

<blockquote><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/78h7xgj">Join the JF Dashboards Discord Server!</a></strong></div><div>A space and community for anyone using Blueprint, Frames or Kuper, to ask questions and get help or support | 411 members</div></blockquote>
