### ISSUE TITLE
Material Design 3 Toggles/Switches

### ISSUE THREAD

**Issue by KoleHoenicke** [jahirfiquitiva/Frames#263]
### Frames Version

3.5.7

### Describe the feature

I would love it if you updated all the toggles/switches in Frames (and Kuper and Blueprint) to use the new Material Design 3 ones. Screenshots in link: [](https://imgur.com/a/TTb2jOU)

**Comment by jahirfiquitiva** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/jahirfiquitiva/Frames/issues/263">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/263/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/263/pledge.svg">
</picture>
</a>

**Comment by pashapuma** [comment]
![Screenshot_20230817-131922](https://github.com/jahirfiquitiva/Frames/assets/26832289/7cdda39d-8d32-4ffe-b02d-a9ed7d43a022)

**Comment by jahirfiquitiva** [comment]
Will be available in the next update
