### ISSUE TITLE
labelVisibilityMode Does not Work

### ISSUE THREAD

**Issue by KoleHoenicke** [jahirfiquitiva/Frames#264]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

3.5.7

### Android Version

14

### Device Manufacturer

Google

### Device Name

Pixel 7 Pro

### What happened?

Having labelVisibilityMode as anything other than auto doesn't work.

### Reproduction Steps

In styles.xml, change <item name="labelVisibilityMode">auto</item> to either labeled, unlabeled, or selected and it won't make any difference in the app.

### Expected behavior

Changing the mode should affect what you see in the app, but it does not.

### Screenshots or videos

https://imgur.com/a/wfmFHp7

### Code and/or Logs

?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="MyApp" />

    
    <style name="MyApp.SplashScreen" parent="Frames.SplashScreen">
        <item name="customFontBold">@font/manrope_bold_fam</item>
        <item name="customFontNormal">@font/manrope_normal_fam</item>
    </style>

    
    <style name="MyApp.Default" parent="Frames.Default">
        <item name="bottomNavigationStyle">@style/MyApp.BottomNavigationView</item>
        <item name="customFontBold">@font/manrope_bold_fam</item>
        <item name="customFontNormal">@font/manrope_normal_fam</item>
    </style>

    
    <style name="MyApp.Default.Amoled" parent="Frames.Default.Amoled">
        <item name="bottomNavigationStyle">@style/MyApp.BottomNavigationView</item>
        <item name="customFontBold">@font/manrope_bold_fam</item>
        <item name="customFontNormal">@font/manrope_normal_fam</item>
    </style>

    
    <style name="MyApp.BottomNavigationView" parent="Widget.Frames.BottomNavigationView">
        
        <item name="labelVisibilityMode">selected</item>
    </style>

</resources>

**Comment by jahirfiquitiva** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/jahirfiquitiva/Frames/issues/264">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/264/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/264/pledge.svg">
</picture>
</a>

**Comment by jahirfiquitiva** [comment]
@kolepsd would you mind adding the code for your modified `styles.xml`

**Comment by KoleHoenicke** [comment]
Added.

**Comment by jahirfiquitiva** [comment]
@kolepsd have you tried updating the styles in the `m3_styles.xml` file?
