### ISSUE TITLE
Valid JSON file still causes "Data is Possibly Malformed" error

### ISSUE THREAD

**Issue by Stoxic** [jahirfiquitiva/Frames#266]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

Blueprint 2.3.9

### Android Version

13.0.0

### Device Manufacturer

One Plus

### Device Name

Oneplus 11

### What happened?

When I open it show a message Data is Possibly Malformed . Contact Developer

### Reproduction Steps

Wallpaper isn't loading. While jason file seems to be Valid

**Comment by jahirfiquitiva** [comment]
Test JSON file: https://drive.google.com/uc?id=1KXn9qXYZO6Z34kpbW21I0uXODkkyG2uF

**Comment by jahirfiquitiva** [comment]
Closing as confirmed to be working in the latest version
