### ISSUE TITLE
Action required: Migrate to supported version of Google Play Billing Library

### ISSUE THREAD

**Issue by Paget96** [jahirfiquitiva/Frames#269]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

3.6.1

### Android Version

14

### Device Manufacturer

Xiaomi

### Device Name

Mi 12t pro

### What happened?

Action required: Migrate to supported version of Google Play Billing Library

May 28, 2024 18:31
We are introducing changes to the lifecycle of Play Billing Library and its associated deprecation timelines. Because you currently use an older version of the library, we wanted you to be aware of new key dates you’ll need to adhere to:

By Aug 31, 2024, all new apps and updates to existing apps must use Billing Library version 6 or newer. If you need more time to update your app, you will be able to request an extension until Nov 1, 2024.

Learn more about the deprecation [here](https://notifications.google.com/g/p/ANiao5oRbKSCp1Ce9Y49-wmnaVm4v8EFW11vnrwnhrsqiXh2BD9-DvoRBF_ZfCtxJ9oxb__HDQTMyMvM0NLHPJ2ONrw6vxkkOKZ7SyCd2mcuZgj5aiC2rn4SdoT9UcOPHIh_wnF_IICySRbqLRIZ6bK5D1H5ZS6v2rGyYja5eQqzgBicf4DshD4knDVU-xB8FHL72wIYt91omrPURVW9aFxHYcLBQbHwFnslFSgajQwQkUg5CJXIQTl6avL00r-gmZlqpHu38bE5fw).

Update before these dates to avoid a disruption in app publishing and updates. Publishing and updating apps that use Play Billing Library version lower than 6 will be blocked in Play Console on the dates mentioned above.

Next steps: More information on how to migrate to the latest version of Play Billing Library can be found on our [developer website](https://notifications.google.com/g/p/ANiao5q2uGnwcx3t_g7LZdbv6guQxh-zOEfv3hfLam0EamQxXAI5borwNFnVTY4y7d5oJaQEZNPKBuFeHd_PWH9uScb7oDghenbC7sxFWmaaTFiekxy1T0-s8p5Llk5L43EU6U2H9mest-GHX7SMJnciPbBZbSvFrZiwyUeQVDX7ZnniPolKNP7nfjWrqSkxmReNfuCML5Lj2d3QanmAE2nRNNB3FWGwQvZ7kGp2awTSgWdnRt6Bcm_LhVsjBDJIki6AimH15TbC9FN-4zQCkXOL6xQ6dQ).

### Reproduction Steps

There are no steps to reproduce, billing just need to be updated to 7.0.0

**Comment by jahirfiquitiva** [comment]
> By Aug 31, 2024, all new apps and updates to existing apps must use Billing Library version 6 or newer

Frames already uses Billing Library 6+

**Comment by Paget96** [comment]
I'm on 3.6.1 lib version and I received this notification from Google.

**Comment by jahirfiquitiva** [comment]
@Paget96 feel free to request for an extension to them. I will try to update the dashboard to use Billing Library 7+ before their deadline (Aug 31, 2024)

**Comment by Paget96** [comment]
Thanks 🫡
