### ISSUE TITLE
Java Source Code Need !

### ISSUE THREAD

**Issue by akashsguptag** [jahirfiquitiva/Frames#27]
I want Java source Code instead Kotlin Because Frame Zip Not Contain Layout Folder I want to Customize App

**Comment by Gowsky** [comment]
Kotlin has nothing to do with your issue. If you want to edit layout files, you need to fork the Frames library source and edit it by yourself.
https://github.com/jahirfiquitiva/Frames/blob/sample/README.md

**Comment by akashsguptag** [comment]
Thank You .. Can You Please Help Me How I create Json in order to show my Wallpaper ..

**Comment by Gowsky** [comment]
Read the wiki.

**Comment by akashsguptag** [comment]
I Read But You Can provide Json File Generator In which I Upload photo daily Means Get New Wallpaper Everyday.
