### ISSUE TITLE
Grid Fragment Stuck in Reload Animation loop after swiping from Collections 

### ISSUE THREAD

**Issue by gusdebbaja** [jahirfiquitiva/Frames#34]
###### Device/dashboard info:
 - Frames version: `2.1.3`
 - Device OS version: `7.0.0`
 - Device Manufacturer: `Samsung S8`

At launch, the application is stuck in the loading animation, and does not display the pictures unless I drag from top to bottom. 

Second, when we select a wallpaper to view, then we go back to the main activity, the activity flickers and re-position itself, for no apparent reason. 

Third, when we navigate to the "Collection" tab, and we go back to the "All" tab, the "All" tab reloads for no reason (?) and is stuck in the loading animation again, until I swipe up to bottom. 

Lastly, even those I set these wallpapers as downloadable, but when I click to view any wallpapers, the download button is not present. 

* [link to the video](https://youtu.be/1-RzkRN3q68)

* [link to json file](https://api.myjson.com/bins/q6y4l.json)

Disclaimer: I changed all of my wallpapers to this wallpaper in respect to the request of the artists. But the numbers of wallpapers remain the same and the behavior of the application did not change.

**Comment by jahirfiquitiva** [comment]
You are not using version 2.1.3 ... 
And you are using the library source.

You can see what happens when you use the library source [here](https://github.com/jahirfiquitiva/Frames#library-source)

**Comment by gusdebbaja** [comment]
In that version I just cloned the sample branch. Not sure how you concluded I am using the library source. I only added my Json file and nothing else.

**Comment by jahirfiquitiva** [comment]
@gusdebbaja 

The new collections view is not available in v 2.1.3 but you have it in the video you uploaded. Same as the download button not appearing which of course has a reason that I will only explain when releasing the new version.

Follow the steps in the [wiki](https://github.com/jahirfiquitiva/Frames/wiki/Importing-The-Project).
