### ISSUE TITLE
Add Option to download in different resolution.

### ISSUE THREAD

**Issue by Nithis111** [jahirfiquitiva/Frames#37]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Frames.

###### Device/dashboard info:
 - Frames version: `New Idea`
 - Device OS version: `New`
 - Device Manufacturer: `New'
 - Device Name: `New`
It will be great if you add feature that app can automatically select user's device resolution and serve wallpaper according to their screen resolution from json

**Comment by jahirfiquitiva** [comment]
That's already done when applying the wallpapers. I won't do it for downloads tho.

Next time please use and fill the issue template properly

**Comment by Nithis111** [comment]
Ok thank you
