### ISSUE TITLE
WallPapers Viewer Activity and Main Layout

### ISSUE THREAD

**Issue by redmi111** [jahirfiquitiva/Frames#38]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Frames.

###### Device/dashboard info:
 - Frames version: `2.1.3`
 - Device OS version: `7.0`
 - Device Manufacturer: `Xioami`
 - Device Name: `Note 4`

When I scroll to middle of wallpapers in MainActivity, I opened one wallpaper and I downloaded that. But when I press back button it goes to first page of recently added wallpapers. Hope you can understand what I coming to say. 

I don't know how to fix it myself.

**Comment by Nithis111** [comment]
Me too noticed this Issue. Dev please fix this. When a user scrolls to bottom of wallpapers and if they download or set any wallpaper then as soon as they click back button that'll take them to first page.

**Comment by jahirfiquitiva** [comment]
1. Update your issue content to use the provided issue template 
2. I couldn't completely understand, so please record a video and put a link to it in the issue

**Comment by jahirfiquitiva** [comment]
Should be fixed since version `2.2.1`. Let me know
