### ISSUE TITLE
Warning:there were 27 unresolved references to classes or interfaces.

### ISSUE THREAD

**Issue by ghost** [jahirfiquitiva/Frames#48]
Warning:ca.allanwang.kau.utils.ActivityUtilsKt: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:ca.allanwang.kau.utils.IIconUtilsKt: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:ca.allanwang.kau.utils.IIconUtilsKt: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:ca.allanwang.kau.utils.IIconUtilsKt: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:ca.allanwang.kau.utils.IIconUtilsKt: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:ca.allanwang.kau.utils.IIconUtilsKt: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:ca.allanwang.kau.utils.IIconUtilsKt: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:ca.allanwang.kau.utils.IIconUtilsKt$toDrawable$1: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:ca.allanwang.kau.utils.ViewUtilsKt: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:ca.allanwang.kau.utils.ViewUtilsKt: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:ca.allanwang.kau.utils.ViewUtilsKt: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:ca.allanwang.kau.utils.ViewUtilsKt$setIcon$1: can't find referenced class com.mikepenz.iconics.IconicsDrawable

- [ x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x] I have verified that I am using the latest version of Frames.

### Device/dashboard info:
 - Frames version: `2.3.2`
 - Android version: `Android Studio`

**Comment by jahirfiquitiva** [comment]
Those are warnings only. Just ignore them. :wink:
