### ISSUE TITLE
Please Help me make some changes to App

### ISSUE THREAD

**Issue by arjunmaan2011** [jahirfiquitiva/Frames#5]
Can You Help to make some changes like add new tab, Navigation Drawer and Image View, Total Downloads Option,Ads and Firebase Analytics.

**Comment by jahirfiquitiva** [comment]
App source is shared **AS IS**. Additional features like the ones you mentioned must be added by yourself.

If you want me to do that for you, you will have to pay for extra service. If you are interested, you can [contact me](mailto:contact@jahirfiquitiva.me)
