### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [jahirfiquitiva/Frames#51]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by jbeguna04** [comment]
Hi, Those proposed issue is not on the template. I would like to propose new designs of logo/icon

**Comment by jahirfiquitiva** [comment]
Hi @jbeguna04 

Thanks for your willing to contribute to the project

I don't have any plans to change the current logo/icon as I think is pretty good already and the change is not really necessary, and also, people already know the current logo and help them recognize the app.

Thanks again, feel free to contribute in other ways if you want to 😊🙌🏼
