### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [jahirfiquitiva/Frames#56]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by jahirfiquitiva** [comment]
Hi... Thanks for your interest on contributing to the project... Feel free to make any PRs to achieve that 😀

**Comment by olayhemy** [comment]
Hello..... Thanks for the approval. I've made a PR but it can't be found on the PR queue.

**Comment by jahirfiquitiva** [comment]
@olayhemy 
You've made a PR for your own repo (the fork of mine). You must create a PR to this repo for it to be shown in the PRs site.

**Comment by olayhemy** [comment]
Heello... @jahirfiquitiva
I've deleted the previous forked repository of yours and I've ve made a new one with all corrections. Please check and merge.

**Comment by olayhemy** [comment]
I'm sorry for any inconveniency
