### ISSUE TITLE
How to add adcode

### ISSUE THREAD

**Issue by charles935** [jahirfiquitiva/Frames#60]
Can u plz tell how to add admob add codes...since there are no layout files...plz tell me where should I place it...can u plz add a demo file for it... Plz help some how plz plz pl

**Comment by jahirfiquitiva** [comment]
Please stop your spam with this issue. It has been already reported/asked about 4 times.

I already mentioned that the app/library is provided **as is**. If you want to add something, you can do it **on your own**. I **do NOT** provide support for such cases.
