### ISSUE TITLE
Proposal for a logo

### ISSUE THREAD

**Issue by olu4mide** [jahirfiquitiva/Frames#61]
Hello, Good day. How you doing? 

I came across your project and even downloaded the app but discovered it has no logo. 

So I decide that as an open source contributor and a graphics designer, I should make one for you. 
The logo can also serve as your icon. Which I will make. 

![frames](https://user-images.githubusercontent.com/36331413/39669875-29f18cc8-50f0-11e8-9329-67abbb26b253.png)
 Here is the logo. I hope you do like it. 

If you have any correction or wants to change the logo, let me know. Or if you have any idea in mind.

**Comment by jahirfiquitiva** [comment]
We already have a logo. The app doesn't use it because it's meant to be just a sample not a real app to daily use.

Thanks anyways for the willing to help
