### ISSUE TITLE
How to paste admob codes

### ISSUE THREAD

**Issue by androidxi** [jahirfiquitiva/Frames#62]
How do I  add an intestitial adcode by admob.bcz with out ad app is just a waste.any helps plz cmt

**Comment by Gowsky** [comment]
There are tons of tutorials all over the internet about adding ads to Android apps. If the app's just a waste, then simply don't use it and make your own.

**Comment by androidxi** [comment]
Then show me a tutotirial that could solve this issues all tutorials are in java at least say in which I should add the code there is no layout files

**Comment by jahirfiquitiva** [comment]
The app/library is provided **as is**. If you want to add something, you can do it **on your own**. We **do NOT** provide support for such cases.
