### ISSUE TITLE
Bottom Sheet doesn't draw behind on-screen navbar (on devices with on-screen navbar)

### ISSUE THREAD

**Issue by SanchithHegde** [jahirfiquitiva/Frames#63]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Frames.

### Device/dashboard info:
 - Frames version: `2.3.5`
 - Android version: `8.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G3 (2015)`

### Reproduction Steps
*This is noticed on devices with on-screen navbar only and when bottom sheet is enabled for displaying wallpaper info.*
1. Go to wallpaper preview screen.
2. Tap on wallpaper info icon (i enclosed in a circle).
3. The bottom sheet displaying wallpaper info is shown.

### Expected Result
The bottom sheet draws up behind the navbar too, maintaining uniformity.

### Actual Result
The bottom sheet doesn't draw behind the navbar, but draws up from the region above it.

### Screenshot

| ![Sscreenshot](https://user-images.githubusercontent.com/22217505/39755966-556539ee-52e5-11e8-9332-34651b4044c2.png "Screenshot of a wallpaper from Blueprint sample app.") |
| :---: |
| *Screenshot of a wallpaper from Blueprint sample app.* |

**Comment by jahirfiquitiva** [comment]
This is android default behavior. The bottom sheet always appear above the navigation bar. Nothing I can do.

**Comment by SanchithHegde** [comment]
Ahh okay.

**Comment by jahirfiquitiva** [comment]
@SanchithHegde I'll reopen this. I think is possible. Anyways, it would require a huge overwrite of the current implementation.

**Comment by SanchithHegde** [comment]
Thank You!

**Comment by jahirfiquitiva** [comment]
Looking good enough on Frames 2.5.3 ... Will keep it like that 😅🤷🏻‍♂️
