### ISSUE TITLE
Image transition glitch

### ISSUE THREAD

**Issue by tehKost** [jahirfiquitiva/Frames#67]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Frames.

### Device/dashboard info:
 - Frames version: `2.3.8`
 - Android version: `8.1.0`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 4`

### Reproduction Steps

1. Tap any image for the first time

### Expected Result
Smooth transition

### Actual Result
Image transition glitch for the first time image loaded, but smooth on sequantional taps
Recorded video: https://www.youtube.com/watch?v=ewdcIlo04WQ

**Comment by jahirfiquitiva** [comment]
@tehKost Is is any better with this version? https://github.com/jahirfiquitiva/Frames/releases/download/test/Frames-v2.3.9-release.apk

<blockquote></blockquote>
