### ISSUE TITLE
French Translation Issues (Screenshots) 

### ISSUE THREAD

**Issue by EpikurProd** [jahirfiquitiva/Frames#76]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `2.4.2`
 - Android version: `7.1.2`
 - Device Manufacturer: `Huawei`
 - Device Name: `Honor 5X`

### Describe the bug
Some string are don't well translate, in french like : "Applying '%1$s'…" => "Application '%1$s'…"
When i download or apply wallpaper, i don't see the wallpaper name. I check on my other app based on 2.3.8 library version, there is no problem.

### Reproduction Steps
1. Open App
2. Choose Wallpaper
3. Download or apply it
4. The windows dialog show "Application '%1$s'…"

### Expected behavior
A worth translation
![screenshot_20180603-140956](https://user-images.githubusercontent.com/19433440/40886503-48cca3e4-6739-11e8-98c8-381f19e1c0ba.png)
![screenshot_20180603-141007](https://user-images.githubusercontent.com/19433440/40886504-48ec3894-6739-11e8-86fd-cd59eccf7be9.png)

### Screenshots
Attached

**Comment by jahirfiquitiva** [comment]
Thanks for the report. This will be fixed in the new version (which will be available in a couple hours 🙂)

**Comment by jahirfiquitiva** [comment]
I'll close this because it's fixed already. Please stay tuned for the new release 😄
