### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by tehKost** [jahirfiquitiva/Frames#78]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `2.4.6`
 - Android version: `8.1 / 7.0 (emulator)`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 4`

### Describe the bug
Memory Leak on scrolling big list of images.
My guess is that there are some references left while loading image with Glide into RecyclerView that prevents garbage collector to free memory.

### Reproduction Steps
1. Add json_url with 200 images
2. Scroll down wallpapers list

### Expected behavior

Memory usage should not grow that big

### Screenshots

[Profiler screenshot](https://i.imgur.com/6lqpn1j.png)

**Comment by tehKost** [comment]
Found out that leak is caused by calling [animateSmoothly](https://github.com/jahirfiquitiva/kext/blob/a2095f9b74a94ff72fd3eb82ce836794a9e597e8/core/src/main/kotlin/jahirfiquitiva/libs/kext/extensions/View.kt#L120), that holds reference to ViewHolder.View in [onUpdate](https://github.com/jahirfiquitiva/kext/blob/a2095f9b74a94ff72fd3eb82ce836794a9e597e8/core/src/main/kotlin/jahirfiquitiva/libs/kext/extensions/View.kt#L116) callback. Any way to clear this listener on recycling view?

**Comment by jahirfiquitiva** [comment]
@tehKost Feel free to create a Pull Request to "fix" these issues
