### ISSUE TITLE
where i can find Layout xml 

### ISSUE THREAD

**Issue by RIadpro** [jahirfiquitiva/Frames#85]
where i can find the layout files so i can change the designs etc

**Comment by jahirfiquitiva** [comment]
https://github.com/jahirfiquitiva/Frames#library-source

<blockquote><img src="https://avatars2.githubusercontent.com/u/10360816?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/jahirfiquitiva/Frames">jahirfiquitiva/Frames</a></strong></div><div>Free, feature-rich, easily customizable Android dashboard for wallpapers apps - jahirfiquitiva/Frames</div></blockquote>
