### ISSUE TITLE
Doesn't load already loaded wallpapers

### ISSUE THREAD

**Issue by nerowhite84** [jahirfiquitiva/Frames#96]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `2.5.3`
 - Android version: `9`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Gemini`

### Describe the bug
loaded images get disappear suddenly, After reloading couple of times it comes back. Even with decent internet the pictures get loaded successfully but somehow it disappears and reload again and again.  

### Expected behavior
I expected frames to load images and keep it as it is. But it reloads and fetch walls from the internet which

### Screenshots

![photo_2018-11-07_09-08-18 2](https://user-images.githubusercontent.com/22963451/48108432-4dd64200-e26d-11e8-8147-0d3dbab4803a.jpg)
![photo_2018-11-07_09-08-18 3](https://user-images.githubusercontent.com/22963451/48108435-4f076f00-e26d-11e8-82b5-6a78223d0499.jpg)
![photo_2018-11-07_09-08-18](https://user-images.githubusercontent.com/22963451/48108436-4f076f00-e26d-11e8-8e58-7249426f2392.jpg)

**Comment by jahirfiquitiva** [comment]
Thanks for the detailed report. I will try to fix it for next update (no eta)

**Comment by jahirfiquitiva** [comment]
Fixed in v `2.6.0`
