### ISSUE TITLE
Support .WEBP format for wallpapers

### ISSUE THREAD

**Issue by Gowsky** [jahirfiquitiva/Frames#99]
### Is your feature request related to a problem? Please describe.
WEBP image format allows much better compression for wallpapers than PNG. While preserving similar quality level as PNG, the WEBP format has much lesser size allowing to load wallpapers faster.

### Describe the solution you'd like
Adding WEBP support for wallpapers

### Describe alternatives you've considered
While JPEG images in general are smaller than PNG, PNG images have better quality. WEBP has both of these advantages.

**Comment by jahirfiquitiva** [comment]
Implemented in v `2.6.0`
